import {useState} from 'react'
import {launchRequest} from './api'
interface Environment{id:string;config:{name:string;type:string};result:{healthy:boolean;latencyMs:number;behind:number|null;commit?:string;error?:string}|null;incidents:Array<{id:string;message:string;count:number}>}
export function PersonalEnvironments({projectId,onConversation}:{projectId:string;onConversation:(id:string)=>void}){
 const [items,setItems]=useState<Environment[]>([]),[hosts,setHosts]=useState<string[]>([]),[error,setError]=useState(''),[name,setName]=useState('Production'),[type,setType]=useState('http'),[url,setUrl]=useState(''),[host,setHost]=useState(''),[service,setService]=useState(''),[directory,setDirectory]=useState('')
 async function load(){try{const data=await launchRequest<{environments:Environment[];hosts:string[]}>(`/api/projects/${projectId}/personal-environments`);setItems(data.environments);setHosts(data.hosts)}catch(error){setError(String(error))}}
 async function save(){try{await launchRequest(`/api/projects/${projectId}/personal-environments`,'POST',{name,type,url,host,service,directory});await load()}catch(error){setError(String(error))}}
 return <section className="chantiers-view" aria-label="Environnements personnels"><button className="secondary-button" onClick={()=>void load()}>Actualiser les environnements personnels</button>{error&&<p role="alert">{error}</p>}{items.map(item=><div key={item.id}><strong>{item.config.name}</strong><p>{item.result?`${item.result.healthy?'Disponible':'Indisponible'} · ${item.result.latencyMs??'?'} ms · retard : ${item.result.behind??'?'} commits`:'Pas encore sondé'}</p><p>{item.result?.error}</p><button className="secondary-button" onClick={()=>void launchRequest(`/api/projects/${projectId}/personal-environments/${item.id}`,'POST',{}).then(load).catch(error=>setError(String(error)))}>Sonder</button>{item.incidents.map(incident=><div key={incident.id}><p>{incident.message} · {incident.count} occurrences</p><button className="secondary-button" onClick={()=>void launchRequest<{id:string}>(`/api/personal-incidents/${incident.id}/triage`,'POST',{}).then(c=>onConversation(c.id)).catch(error=>setError(String(error)))}>Lancer un triage</button></div>)}</div>)}
 <details><summary>Ajouter un environnement</summary><label>Nom<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Type<select value={type} onChange={e=>setType(e.target.value)}><option value="http">HTTP</option><option value="ssh-systemd">SSH · systemd</option><option value="ssh-docker">SSH · Docker</option></select></label>{type==='http'?<label>URL de santé<input value={url} onChange={e=>setUrl(e.target.value)}/></label>:<><label>Hôte SSH<select value={host} onChange={e=>setHost(e.target.value)}><option value="">Choisir…</option>{hosts.map(x=><option key={x}>{x}</option>)}</select></label><label>Service ou conteneur<input value={service} onChange={e=>setService(e.target.value)}/></label><label>Répertoire Git<input value={directory} onChange={e=>setDirectory(e.target.value)}/></label></>}<button className="primary-button" onClick={()=>void save()}>Enregistrer l’environnement</button></details></section>
}
