export class SentryHttpError extends Error { constructor(public status:number,message:string){super(message);this.name="SentryHttpError";} }
export class SentryAuthError extends SentryHttpError { constructor(status:number){super(status,"Sentry authentication failed");this.name="SentryAuthError";} }
export interface SentryIssueSummary {id:string;shortId:string;project:string;title:string;culprit:string|null;transaction:string|null;level:string;status:string;count:number;userCount:number;firstSeen:string;lastSeen:string;permalink:string;release:string|null;tags:Record<string,string[]>}
type FetchLike = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
export class SentryClient {
 private baseUrl:string; private token:string; private fetchImpl:FetchLike;
 constructor(input:{baseUrl:string;token:string;fetchImpl?:FetchLike}){this.baseUrl=input.baseUrl.replace(/\/$/,"");this.token=input.token;this.fetchImpl=input.fetchImpl??fetch;}
 async listIssues(input:{org:string;project:string;environment:"production";statsPeriod:string;query:string}):Promise<SentryIssueSummary[]>{const p=new URLSearchParams({environment:input.environment,statsPeriod:input.statsPeriod,query:input.query,per_page:"50"});const rows=await this.request<any[]>(`/api/0/projects/${encodeURIComponent(input.org)}/${encodeURIComponent(input.project)}/issues/?${p}`);return rows.map(r=>({id:String(r.id),shortId:String(r.shortId??r.short_id??""),project:String(r.project?.slug??input.project),title:String(r.title??""),culprit:r.culprit?String(r.culprit):null,transaction:r.metadata?.transaction?String(r.metadata.transaction):null,level:String(r.level??"error"),status:String(r.status??""),count:Number(r.count??0),userCount:Number(r.userCount??0),firstSeen:String(r.firstSeen??""),lastSeen:String(r.lastSeen??""),permalink:String(r.permalink??""),release:r.firstRelease?.version?String(r.firstRelease.version):null,tags:{}}));}
 issueDetail(org:string,id:string){return this.request(`/api/0/organizations/${encodeURIComponent(org)}/issues/${encodeURIComponent(id)}/`);}
 issueEvents(org:string,id:string,input:{environment:"production";statsPeriod:string}){const p=new URLSearchParams(input);return this.request(`/api/0/organizations/${encodeURIComponent(org)}/issues/${encodeURIComponent(id)}/events/?${p}`);}
 eventDetail(org:string,project:string,id:string){return this.request(`/api/0/projects/${encodeURIComponent(org)}/${encodeURIComponent(project)}/events/${encodeURIComponent(id)}/`);}
 private async request<T>(path:string):Promise<T>{let response=await this.fetchImpl(`${this.baseUrl}${path}`,{headers:{authorization:`Bearer ${this.token}`,accept:"application/json"}});if([429,502,503,504].includes(response.status))response=await this.fetchImpl(`${this.baseUrl}${path}`,{headers:{authorization:`Bearer ${this.token}`,accept:"application/json"}});if(response.status===401||response.status===403)throw new SentryAuthError(response.status);if(!response.ok)throw new SentryHttpError(response.status,`Sentry request failed: ${response.status}`);return response.json() as Promise<T>;}
}
